### ISSUE TITLE
Style transformation for SVG broken since 3.23

### ISSUE THREAD

**Issue by kartikrao** [imgproxy/imgproxy#1284]
![Screen Shot 2023-09-20 at 10 35 27](https://github.com/imgproxy/imgproxy/assets/736365/a0e6c9d5-4fb3-4fc9-b761-c01416c2b662)

Tried style out, but unfortunately I _cannot get it to work_.

Here is an example URL where I've attempted to color an SVG icon per your instructions above.
`http://localhost:8080/unsafe/st:KiB7ZmlsbDogI2NjYyAhaW1wb3J0YW50fQ/plain/https://images.drive.com.au/driveau/image/upload/v1/cms/theme/icons/HamburgerMenuIconStraight`

I can see its being picked up and interpreted by imgproxy looking at the logs
```INFO    [2023-09-20T00:32:06Z] Completed in 63.856542ms /unsafe/st:KiB7ZmlsbDogI2NjYyAhaW1wb3J0YW50fQ/plain/https://images.drive.com.au/driveau/image/upload/v1/cms/theme/icons/HamburgerMenuIconStraight  request_id=eQzZpiV_LP_UTcmDLbLL3 method=GET status=200 client_ip=172.17.0.1 image_url="https://images.drive.com.au/driveau/image/upload/v1/cms/theme/icons/HamburgerMenuIconStraight" processing_options="Style: * {fill: #ccc !important}"```

However in the resultant image there is no style node in the output.
![Screen Shot 2023-09-20 at 10 34 39](https://github.com/imgproxy/imgproxy/assets/736365/505d09bb-1ee9-42f3-b626-4399a8eb4346)

![Screen Shot 2023-09-20 at 10 36 42](https://github.com/imgproxy/imgproxy/assets/736365/0cbde4b3-dacb-452a-83c2-28c5d651e04f)

What am I doing wrong ?

_Originally posted by @kartikrao in https://github.com/imgproxy/imgproxy/issues/1202#issuecomment-1726722082_

**Comment by DarthSim** [comment]
Fixed in the `latest` build

**Comment by kartikrao** [comment]
@DarthSim - I've tried both 3.24.1 and latest and they both still have the issue.

**Comment by DarthSim** [comment]
I guess you're trying an old `latest`. What's the SHA of the image you're using?

I basically just reverted the changes that caused the issue.
